name: sngine_messenger
description: Sngine Messnger

version: 1.0.0+3

environment:
 sdk: ">=3.4.0 <4.0.0"

dependencies:
 flutter:
  sdk: flutter

 cupertino_icons: ^1.0.8
 onesignal_flutter: ^5.3.0
 http: ^1.3.0
 intl: ^0.19.0
 shared_preferences: ^2.5.3
 image_picker: ^1.1.2
 url_launcher: ^6.3.1
 flutter_svg: ^2.1.0
 path_provider: ^2.1.5
 crypto: ^3.0.6
 permission_handler: ^12.0.0+1
 record: ^6.0.0

 auto_route: ^10.0.1
 flutter_riverpod: ^2.6.1
 uuid: ^4.4.2
 device_info_plus: ^11.3.3
 cached_network_image: ^3.4.1
 easy_localization: ^3.0.7+1
 timeago_flutter: ^3.7.0
 share_plus: ^11.0.0

 flutter_slidable: ^4.0.0
 flutter_spinkit: ^5.2.1
 flutter_html: ^3.0.0-beta.2
 multi_select_flutter: ^4.1.3
 pinput: ^5.0.1
 qr_flutter: ^4.1.0

 voice_message_package: ^2.2.1
 photo_view: ^0.14.0
 flutter_image_gallery_saver: ^0.0.2

dev_dependencies:
 flutter_test:
  sdk: flutter

 build_runner: ^2.4.15
 auto_route_generator: ^10.0.1
 flutter_lints: ^5.0.0
 custom_lint: ^0.7.3
 riverpod_lint: ^2.3.10
 logger: ^2.5.0

flutter:
 uses-material-design: true

 assets:
  - assets/images/
  - assets/images/icons/
  - assets/images/icons/chat/
  - assets/images/icons/navbar/
  - assets/images/icons/settings/
  - assets/images/icons/social/
  - assets/images/snackbars/
  - assets/images/snackbars/types/
  - assets/translations/

 fonts:
  - family: Poppins
    fonts:
     - asset: assets/fonts/Poppins/Poppins-Regular.ttf
     - asset: assets/fonts/Poppins/Poppins-Bold.ttf
       weight: 700
     - asset: assets/fonts/Poppins/Poppins-Light.ttf
       weight: 300
  - family: Tajawal
    fonts:
     - asset: assets/fonts/Tajawal/Tajawal-Regular.ttf
     - asset: assets/fonts/Tajawal/Tajawal-Bold.ttf
       weight: 700
     - asset: assets/fonts/Tajawal/Tajawal-Light.ttf
       weight: 300
